tomokv-nodes 4
tomokv-pin-mode static
tomokv-pin-ex "node0=0-3 node1=8-11 node2=16-19 node3=24-27"
tomokv-pin-io "node0=4-7 node1=12-15 node2=20-23 node3=28-31"
tomokv-thread-mode static
tomokv-thread-io 4
tomokv-thread-ex 4
port 6380
bind 127.0.0.1
protected-mode no
save ""
appendonly no
enable-debug-command yes
