tomokv-nodes 4
tomokv-pin-mode static
tomokv-pin-ex "node0=64-67 node1=72-75 node2=80-83 node3=88-91"
tomokv-pin-io "node0=68-71 node1=76-79 node2=84-87 node3=92-95"
tomokv-thread-mode static
tomokv-thread-io 4
tomokv-thread-ex 4
port 6381
bind 127.0.0.1
protected-mode no
save ""
appendonly no
enable-debug-command yes
