# tomokv-costs v1 sha=766b135d date=2026-08-25T17:57:44Z backend=uring atomic=0 nodes=1 io=1 ex=7
cell cmd=mget argc=9-16 bytes=<256B ex_us=1.402344 folds=7 state=frozen
cell cmd=mset argc=17-32 bytes=<256B ex_us=4.761719 folds=7 state=frozen
