// Generated by tools/gen_acl_categories.py from vanilla Redis 7.4; do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace tomo {

struct AclCategoryDefinition {
    const char* name;
    uint64_t bit;
};

inline constexpr AclCategoryDefinition kAclCategories[] = {
    {"keyspace", uint64_t{1} << 0},
    {"read", uint64_t{1} << 1},
    {"write", uint64_t{1} << 2},
    {"set", uint64_t{1} << 3},
    {"sortedset", uint64_t{1} << 4},
    {"list", uint64_t{1} << 5},
    {"hash", uint64_t{1} << 6},
    {"string", uint64_t{1} << 7},
    {"bitmap", uint64_t{1} << 8},
    {"hyperloglog", uint64_t{1} << 9},
    {"geo", uint64_t{1} << 10},
    {"stream", uint64_t{1} << 11},
    {"pubsub", uint64_t{1} << 12},
    {"admin", uint64_t{1} << 13},
    {"fast", uint64_t{1} << 14},
    {"slow", uint64_t{1} << 15},
    {"blocking", uint64_t{1} << 16},
    {"dangerous", uint64_t{1} << 17},
    {"connection", uint64_t{1} << 18},
    {"transaction", uint64_t{1} << 19},
    {"scripting", uint64_t{1} << 20},
};
inline constexpr std::size_t kAclCategoryCount =
    sizeof(kAclCategories) / sizeof(kAclCategories[0]);

struct AclCommandCategoryDefinition {
    const char* name;
    uint64_t categories;
};

inline constexpr AclCommandCategoryDefinition kAclCommandCategories[] = {
    {"ACL", 0x0000000000008000ULL}, // slow
    {"APPEND", 0x0000000000004084ULL}, // write string fast
    {"AUTH", 0x0000000000044000ULL}, // fast connection
    {"BGREWRITEAOF", 0x000000000002a000ULL}, // admin slow dangerous
    {"BGSAVE", 0x000000000002a000ULL}, // admin slow dangerous
    {"BITCOUNT", 0x0000000000008102ULL}, // read bitmap slow
    {"BITFIELD", 0x0000000000008104ULL}, // write bitmap slow
    {"BITFIELD_RO", 0x0000000000004102ULL}, // read bitmap fast
    {"BITOP", 0x0000000000008104ULL}, // write bitmap slow
    {"BITPOS", 0x0000000000008102ULL}, // read bitmap slow
    {"BLMOVE", 0x0000000000018024ULL}, // write list slow blocking
    {"BLMPOP", 0x0000000000018024ULL}, // write list slow blocking
    {"BLPOP", 0x0000000000018024ULL}, // write list slow blocking
    {"BRPOP", 0x0000000000018024ULL}, // write list slow blocking
    {"BRPOPLPUSH", 0x0000000000018024ULL}, // write list slow blocking
    {"BZMPOP", 0x0000000000018014ULL}, // write sortedset slow blocking
    {"BZPOPMAX", 0x0000000000014014ULL}, // write sortedset fast blocking
    {"BZPOPMIN", 0x0000000000014014ULL}, // write sortedset fast blocking
    {"CLIENT", 0x0000000000008000ULL}, // slow
    {"COMMAND", 0x0000000000048000ULL}, // slow connection
    {"CONFIG", 0x0000000000008000ULL}, // slow
    {"COPY", 0x0000000000008005ULL}, // keyspace write slow
    {"DBSIZE", 0x0000000000004003ULL}, // keyspace read fast
    {"DEBUG", 0x000000000002a000ULL}, // admin slow dangerous
    {"DECR", 0x0000000000004084ULL}, // write string fast
    {"DECRBY", 0x0000000000004084ULL}, // write string fast
    {"DEL", 0x0000000000008005ULL}, // keyspace write slow
    {"DISCARD", 0x0000000000084000ULL}, // fast transaction
    {"DUMP", 0x0000000000008003ULL}, // keyspace read slow
    {"ECHO", 0x0000000000044000ULL}, // fast connection
    {"EVAL", 0x0000000000108000ULL}, // slow scripting
    {"EVALSHA", 0x0000000000108000ULL}, // slow scripting
    {"EXEC", 0x0000000000088000ULL}, // slow transaction
    {"EXISTS", 0x0000000000004003ULL}, // keyspace read fast
    {"EXPIRE", 0x0000000000004005ULL}, // keyspace write fast
    {"EXPIREAT", 0x0000000000004005ULL}, // keyspace write fast
    {"EXPIRETIME", 0x0000000000004003ULL}, // keyspace read fast
    {"FLUSHALL", 0x0000000000028005ULL}, // keyspace write slow dangerous
    {"FLUSHDB", 0x0000000000028005ULL}, // keyspace write slow dangerous
    {"GEOADD", 0x0000000000008404ULL}, // write geo slow
    {"GEODIST", 0x0000000000008402ULL}, // read geo slow
    {"GEOHASH", 0x0000000000008402ULL}, // read geo slow
    {"GEOPOS", 0x0000000000008402ULL}, // read geo slow
    {"GEORADIUS", 0x0000000000008404ULL}, // write geo slow
    {"GEORADIUSBYMEMBER", 0x0000000000008404ULL}, // write geo slow
    {"GEORADIUSBYMEMBER_RO", 0x0000000000008402ULL}, // read geo slow
    {"GEORADIUS_RO", 0x0000000000008402ULL}, // read geo slow
    {"GEOSEARCH", 0x0000000000008402ULL}, // read geo slow
    {"GEOSEARCHSTORE", 0x0000000000008404ULL}, // write geo slow
    {"GET", 0x0000000000004082ULL}, // read string fast
    {"GETBIT", 0x0000000000004102ULL}, // read bitmap fast
    {"GETDEL", 0x0000000000004084ULL}, // write string fast
    {"GETEX", 0x0000000000004084ULL}, // write string fast
    {"GETRANGE", 0x0000000000008082ULL}, // read string slow
    {"GETSET", 0x0000000000004084ULL}, // write string fast
    {"HDEL", 0x0000000000004044ULL}, // write hash fast
    {"HELLO", 0x0000000000044000ULL}, // fast connection
    {"HEXISTS", 0x0000000000004042ULL}, // read hash fast
    {"HGET", 0x0000000000004042ULL}, // read hash fast
    {"HGETALL", 0x0000000000008042ULL}, // read hash slow
    {"HINCRBY", 0x0000000000004044ULL}, // write hash fast
    {"HINCRBYFLOAT", 0x0000000000004044ULL}, // write hash fast
    {"HKEYS", 0x0000000000008042ULL}, // read hash slow
    {"HLEN", 0x0000000000004042ULL}, // read hash fast
    {"HMGET", 0x0000000000004042ULL}, // read hash fast
    {"HMSET", 0x0000000000004044ULL}, // write hash fast
    {"HRANDFIELD", 0x0000000000008042ULL}, // read hash slow
    {"HSCAN", 0x0000000000008042ULL}, // read hash slow
    {"HSET", 0x0000000000004044ULL}, // write hash fast
    {"HSETNX", 0x0000000000004044ULL}, // write hash fast
    {"HSTRLEN", 0x0000000000004042ULL}, // read hash fast
    {"HVALS", 0x0000000000008042ULL}, // read hash slow
    {"INCR", 0x0000000000004084ULL}, // write string fast
    {"INCRBY", 0x0000000000004084ULL}, // write string fast
    {"INCRBYFLOAT", 0x0000000000004084ULL}, // write string fast
    {"INFO", 0x0000000000028000ULL}, // slow dangerous
    {"KEYS", 0x0000000000028003ULL}, // keyspace read slow dangerous
    {"LASTSAVE", 0x0000000000026000ULL}, // admin fast dangerous
    {"LINDEX", 0x0000000000008022ULL}, // read list slow
    {"LINSERT", 0x0000000000008024ULL}, // write list slow
    {"LLEN", 0x0000000000004022ULL}, // read list fast
    {"LMOVE", 0x0000000000008024ULL}, // write list slow
    {"LMPOP", 0x0000000000008024ULL}, // write list slow
    {"LPOP", 0x0000000000004024ULL}, // write list fast
    {"LPOS", 0x0000000000008022ULL}, // read list slow
    {"LPUSH", 0x0000000000004024ULL}, // write list fast
    {"LPUSHX", 0x0000000000004024ULL}, // write list fast
    {"LRANGE", 0x0000000000008022ULL}, // read list slow
    {"LREM", 0x0000000000008024ULL}, // write list slow
    {"LSET", 0x0000000000008024ULL}, // write list slow
    {"LTRIM", 0x0000000000008024ULL}, // write list slow
    {"MGET", 0x0000000000004082ULL}, // read string fast
    {"MSET", 0x0000000000008084ULL}, // write string slow
    {"MSETNX", 0x0000000000008084ULL}, // write string slow
    {"MULTI", 0x0000000000084000ULL}, // fast transaction
    {"OBJECT", 0x0000000000008000ULL}, // slow
    {"PERSIST", 0x0000000000004005ULL}, // keyspace write fast
    {"PEXPIRE", 0x0000000000004005ULL}, // keyspace write fast
    {"PEXPIREAT", 0x0000000000004005ULL}, // keyspace write fast
    {"PEXPIRETIME", 0x0000000000004003ULL}, // keyspace read fast
    {"PFADD", 0x0000000000004204ULL}, // write hyperloglog fast
    {"PFCOUNT", 0x0000000000008202ULL}, // read hyperloglog slow
    {"PFMERGE", 0x0000000000008204ULL}, // write hyperloglog slow
    {"PING", 0x0000000000044000ULL}, // fast connection
    {"PSETEX", 0x0000000000008084ULL}, // write string slow
    {"PSUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"PTTL", 0x0000000000004003ULL}, // keyspace read fast
    {"PUBLISH", 0x0000000000005000ULL}, // pubsub fast
    {"PUBSUB", 0x0000000000008000ULL}, // slow
    {"PUNSUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"QUIT", 0x0000000000044000ULL}, // fast connection
    {"RANDOMKEY", 0x0000000000008003ULL}, // keyspace read slow
    {"RENAME", 0x0000000000008005ULL}, // keyspace write slow
    {"RENAMENX", 0x0000000000004005ULL}, // keyspace write fast
    {"RESET", 0x0000000000044000ULL}, // fast connection
    {"RESTORE", 0x0000000000028005ULL}, // keyspace write slow dangerous
    {"RPOP", 0x0000000000004024ULL}, // write list fast
    {"RPOPLPUSH", 0x0000000000008024ULL}, // write list slow
    {"RPUSH", 0x0000000000004024ULL}, // write list fast
    {"RPUSHX", 0x0000000000004024ULL}, // write list fast
    {"SADD", 0x000000000000400cULL}, // write set fast
    {"SAVE", 0x000000000002a000ULL}, // admin slow dangerous
    {"SCAN", 0x0000000000008003ULL}, // keyspace read slow
    {"SCARD", 0x000000000000400aULL}, // read set fast
    {"SCRIPT", 0x0000000000008000ULL}, // slow
    {"SDIFF", 0x000000000000800aULL}, // read set slow
    {"SDIFFSTORE", 0x000000000000800cULL}, // write set slow
    {"SELECT", 0x0000000000044000ULL}, // fast connection
    {"SET", 0x0000000000008084ULL}, // write string slow
    {"SETBIT", 0x0000000000008104ULL}, // write bitmap slow
    {"SETEX", 0x0000000000008084ULL}, // write string slow
    {"SETNX", 0x0000000000004084ULL}, // write string fast
    {"SETRANGE", 0x0000000000008084ULL}, // write string slow
    {"SINTER", 0x000000000000800aULL}, // read set slow
    {"SINTERCARD", 0x000000000000800aULL}, // read set slow
    {"SINTERSTORE", 0x000000000000800cULL}, // write set slow
    {"SISMEMBER", 0x000000000000400aULL}, // read set fast
    {"SMEMBERS", 0x000000000000800aULL}, // read set slow
    {"SMISMEMBER", 0x000000000000400aULL}, // read set fast
    {"SMOVE", 0x000000000000400cULL}, // write set fast
    {"SORT", 0x000000000002803cULL}, // write set sortedset list slow dangerous
    {"SPOP", 0x000000000000400cULL}, // write set fast
    {"SPUBLISH", 0x0000000000005000ULL}, // pubsub fast
    {"SRANDMEMBER", 0x000000000000800aULL}, // read set slow
    {"SREM", 0x000000000000400cULL}, // write set fast
    {"SSCAN", 0x000000000000800aULL}, // read set slow
    {"SSUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"STRLEN", 0x0000000000004082ULL}, // read string fast
    {"SUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"SUNION", 0x000000000000800aULL}, // read set slow
    {"SUNIONSTORE", 0x000000000000800cULL}, // write set slow
    {"SUNSUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"TOUCH", 0x0000000000004003ULL}, // keyspace read fast
    {"TTL", 0x0000000000004003ULL}, // keyspace read fast
    {"TYPE", 0x0000000000004003ULL}, // keyspace read fast
    {"UNLINK", 0x0000000000004005ULL}, // keyspace write fast
    {"UNSUBSCRIBE", 0x0000000000009000ULL}, // pubsub slow
    {"UNWATCH", 0x0000000000084000ULL}, // fast transaction
    {"WATCH", 0x0000000000084000ULL}, // fast transaction
    {"XADD", 0x0000000000004804ULL}, // write stream fast
    {"XDEL", 0x0000000000004804ULL}, // write stream fast
    {"XLEN", 0x0000000000004802ULL}, // read stream fast
    {"XRANGE", 0x0000000000008802ULL}, // read stream slow
    {"XREAD", 0x0000000000018802ULL}, // read stream slow blocking
    {"XREVRANGE", 0x0000000000008802ULL}, // read stream slow
    {"XTRIM", 0x0000000000008804ULL}, // write stream slow
    {"ZADD", 0x0000000000004014ULL}, // write sortedset fast
    {"ZCARD", 0x0000000000004012ULL}, // read sortedset fast
    {"ZCOUNT", 0x0000000000004012ULL}, // read sortedset fast
    {"ZDIFF", 0x0000000000008012ULL}, // read sortedset slow
    {"ZDIFFSTORE", 0x0000000000008014ULL}, // write sortedset slow
    {"ZINCRBY", 0x0000000000004014ULL}, // write sortedset fast
    {"ZINTER", 0x0000000000008012ULL}, // read sortedset slow
    {"ZINTERCARD", 0x0000000000008012ULL}, // read sortedset slow
    {"ZINTERSTORE", 0x0000000000008014ULL}, // write sortedset slow
    {"ZLEXCOUNT", 0x0000000000004012ULL}, // read sortedset fast
    {"ZMPOP", 0x0000000000008014ULL}, // write sortedset slow
    {"ZMSCORE", 0x0000000000004012ULL}, // read sortedset fast
    {"ZPOPMAX", 0x0000000000004014ULL}, // write sortedset fast
    {"ZPOPMIN", 0x0000000000004014ULL}, // write sortedset fast
    {"ZRANDMEMBER", 0x0000000000008012ULL}, // read sortedset slow
    {"ZRANGE", 0x0000000000008012ULL}, // read sortedset slow
    {"ZRANGEBYLEX", 0x0000000000008012ULL}, // read sortedset slow
    {"ZRANGEBYSCORE", 0x0000000000008012ULL}, // read sortedset slow
    {"ZRANGESTORE", 0x0000000000008014ULL}, // write sortedset slow
    {"ZRANK", 0x0000000000004012ULL}, // read sortedset fast
    {"ZREM", 0x0000000000004014ULL}, // write sortedset fast
    {"ZREMRANGEBYLEX", 0x0000000000008014ULL}, // write sortedset slow
    {"ZREMRANGEBYRANK", 0x0000000000008014ULL}, // write sortedset slow
    {"ZREMRANGEBYSCORE", 0x0000000000008014ULL}, // write sortedset slow
    {"ZREVRANGE", 0x0000000000008012ULL}, // read sortedset slow
    {"ZREVRANGEBYLEX", 0x0000000000008012ULL}, // read sortedset slow
    {"ZREVRANGEBYSCORE", 0x0000000000008012ULL}, // read sortedset slow
    {"ZREVRANK", 0x0000000000004012ULL}, // read sortedset fast
    {"ZSCAN", 0x0000000000008012ULL}, // read sortedset slow
    {"ZSCORE", 0x0000000000004012ULL}, // read sortedset fast
    {"ZUNION", 0x0000000000008012ULL}, // read sortedset slow
    {"ZUNIONSTORE", 0x0000000000008014ULL}, // write sortedset slow
};
inline constexpr std::size_t kAclCommandCategoryCount =
    sizeof(kAclCommandCategories) / sizeof(kAclCommandCategories[0]);

}  // namespace tomo
