#!/usr/bin/env python3
"""Pinned-source replay; synthetic fallback is explicitly not a measured burst trace.

Reference extraction changes only include paths and namespaces; both complete
detector implementations and the study's actual IoTenure are compiled unchanged.
No server, load generator, timing benchmark or PMU measurement is invoked.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / 'build/wbland2'
STUDY = '60e4221ec5cf36425eb339d3eca608c1a1e64a6d'
PREVIOUS = 'f6d2e969f'


def git_source(commit, path):
    return subprocess.check_output(['git', 'show', f'{commit}:{path}'], cwd=ROOT, text=True)


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def window(source):
    start = source.index('struct Window {')
    return source[start:source.index('\n};', start) + 3]


def reference():
    BUILD.mkdir(parents=True, exist_ok=True)
    study = git_source(STUDY, 'src/core/wbmode.h')
    old = git_source(PREVIOUS, 'src/core/wb_rule.h')
    clock = git_source(STUDY, 'src/core/signalacct.h')
    assert window(study) == window((ROOT/'src/core/wb_rule.h').read_text()), 'literal study Window port changed'
    # The entire original study header stays independent of production. Its
    # unused fixed-rule declarations get a separate namespace to avoid overloads.
    study = study.replace('"../net/conn.h"', '"src/net/conn.h"')
    study = study.replace('namespace tomo::wb_rule', 'namespace tomo::wbland2_reference_rule')
    study = study.replace('wb_rule::', 'wbland2_reference_rule::')
    old = old.replace('"../net/conn.h"', '"src/net/conn.h"')
    old = old.replace('namespace tomo::wb_rule', 'namespace tomo::wbland1')
    clock = clock.replace('"signal.h"', '"src/core/signal.h"')
    clock = clock.replace('namespace tomo {', 'namespace tomo::wbland2_study_clock {')
    (BUILD/'reference.h').write_text('// Generated by tests/wbland2_checks.py reference.\n' + study + '\n' + old + '\n' + clock)
    print('PASS wbland2 reference: literal study Window; independent pinned study/wbland1/clock sources')


def synthetic_trace():
    # Persist deterministic input before replay. This is a synthetic 100ms burst,
    # never represented as a recording of the maintainer's 931K session.
    path = BUILD/'synthetic-burst.csv'
    wall = idle = step = 0
    with path.open('w') as out:
        out.write('# provenance=synthetic; not a live busy-fraction recording\n')
        out.write('# 20ms warm, 100ms burst, 40ms recovery, 20ms idle; uneven passes\n')
        out.write('tenure,wall_ns,idle_ns,owned\n0,0,0,16\n')
        for duration, busy in ((20000000, 64), (100000000, 240), (40000000, 32), (20000000, 0)):
            end = wall + duration
            while wall < end:
                dt = min((1024, 8192, 2048, 32768, 4096)[step % 5], end-wall)
                # Sustained all-busy blocks inside the burst plus short idle
                # troughs; other phases alternate pass demand around their mean.
                b = (256 if (step//64) % 4 else 192) if busy == 240 else min(256, 2*busy) if step % 2 else 0
                idle += dt*(256-b)//256
                wall += dt
                owned = (16, 8, 32, 1, 0)[(step//257) % 5]
                out.write(f'0,{wall},{idle},{owned}\n')
                step += 1
        # A fresh tenure plus zero-duration intervals exercise reset/hold.
        wall += 1000000
        out.write(f'1,{wall},0,1\n1,{wall},0,1\n')
        for i in range(1, 65):
            out.write(f'1,{wall+i*1000},{max(0, i-32)*1000},1\n')
    return path


def check(trace=None):
    BUILD.mkdir(parents=True, exist_ok=True)
    path = trace.resolve() if trace else synthetic_trace()
    rows = []
    for namespace in ('', 'db0-'):
        binary = ROOT/f'build/wbland2-{namespace}replay'
        sequence = BUILD/f'{namespace}sequence.csv'
        for mutant in (False, True):
            args = [str(binary), str(path), str(sequence) + ('.mutant' if mutant else '')]
            if mutant: args.append('--cut-gated')
            result = subprocess.run(args, cwd=ROOT, text=True, capture_output=True, timeout=60)
            marker = ('FAIL wbland2 replay: candidate f sequence equals pinned pol2-k1 on every pass'
                      if mutant else 'PASS wbland2 replay:')
            assert result.returncode == (1 if mutant else 0) and marker in result.stdout+result.stderr, result
            print(result.stdout+result.stderr, end='')
            rows.append(dict(binary=str(binary.relative_to(ROOT)), sha256=digest(binary),
                             negative_control=mutant, exit=result.returncode,
                             stdout=result.stdout, stderr=result.stderr))
    # Confirm that production's two hooks and the study's two hooks use the
    # same unconditional timestamp/idle/count inputs, before any sample beat.
    for file in ('src/core/io_loop.h', 'src/core/reorder.cc'):
        hook = ('const uint64_t pass_ns = tenure.pass();\n' +
                ('            ' if file.endswith('.h') else '        ') +
                'wb_policy.pass(pass_ns, sig.idle_ns, self_->clients().size());')
        assert hook in git_source(STUDY, file) and hook in (ROOT/file).read_text(), file
    report = dict(study_commit=STUDY, previous_commit=PREVIOUS,
                  trace=str(path), trace_sha256=digest(path),
                  provenance='caller-supplied; see trace provenance' if trace else 'synthetic, not live-recorded',
                  reference_sha256=digest(BUILD/'reference.h'), rows=rows,
                  sequence_sha256=digest(BUILD/'sequence.csv'))
    (BUILD/'replay-proof.json').write_text(json.dumps(report, indent=2)+'\n')
    print('PASS wbland2 replay: 4/4 strict outcomes; actual eager/100us clocks agree; cut-gated mutant rejected')


def costs():
    sys.path.insert(0, str(ROOT/'tools'))
    from lbstall_artifacts import Elf
    tracer = BUILD/'instruction-trace'
    subprocess.run(['g++', '-std=c++20', '-O2', '-g', '-Wall', '-Wextra', '-march=native',
                    '-pthread', str(ROOT/'tools/wb_rule_2s_trace.cc'), '-o', str(tracer)], check=True)
    binary = ROOT/'build/wbland2-replay'
    elf = Elf(binary); section = elf.sections[elf.names.index('.text')]
    rows = []
    for arm, symbol_name in (('pre', 'wbland1_cost_tick'), ('post', 'wbland2_cost_tick'), ('pol2', 'pol2_cost_tick')):
        symbol = next(s for s in elf.symbols if s['name'] == symbol_name)
        for case in ('fixed', 'pass', 'close'):
            output = subprocess.check_output([str(tracer), str(binary), f'{arm}-{case}',
                                              hex(symbol['value']), hex(section[3]), hex(section[5]),
                                              str(int(elf.kind == 3))], text=True)
            row = dict(arm=arm, case=case, **json.loads(output.split('TRACE=')[1]))
            rows.append(row); print(json.dumps(row), flush=True)
    (BUILD/'costs.json').write_text(json.dumps(rows, indent=2)+'\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=('reference', 'check', 'costs'))
    parser.add_argument('--trace', type=Path, help='CSV: tenure,wall_ns,idle_ns,owned; relative idle resets per tenure')
    args = parser.parse_args()
    if args.action == 'check': check(args.trace)
    else: {'reference': reference, 'costs': costs}[args.action]()
