#!/usr/bin/env python3
"""Prepare a throwaway AT1/AT2 PRE twin under build/, retaining the new bug counter/tests.

No production file is edited and nothing is executed. Build the generated targets with:
    taskset -c 112-127 make -j16 -f build/atomfix-controls.mk atomfix-controls
The serverless PRE unit must fail at the same data assertions the POST unit passes.
Never run the PRE server against production data; it exists only for mainline's isolated check.
"""
from pathlib import Path
import shutil


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError(f"expected exactly one cut site: {old!r}")
    return text.replace(old, new)


def main():
    root = Path(__file__).resolve().parents[1]
    control = root / "build/atomfix-pre"
    shutil.copytree(root / "src", control / "src", dirs_exist_ok=True)
    path = control / "src/cmd/scatter_engine.inc"
    text = path.read_text()
    text = replace_once(text,
                        "                        UINT64_MAX, state.origin_conn_id);",
                        "                        state.atomic_pop ? UINT64_MAX : state.snapshot, state.origin_conn_id);")
    old = "*state.server, shard, op.arg(key.arg), key.hash, UINT64_MAX,"
    if text.count(old) != 3:
        raise RuntimeError("expected the phase-two, MSET and DEL/UNLINK cut sites")
    text = text.replace(old, "*state.server, shard, op.arg(key.arg), key.hash, state.snapshot,")
    path.write_text(text)
    path = control / "src/cmd/blocking.inc"
    path.write_text(replace_once(path.read_text(),
                                "const uint64_t snapshot = UINT64_MAX;",
                                "const uint64_t snapshot = state.server->atomic_snapshot();"))
    (root / "build/atomfix-controls.mk").write_text("""# Generated by tools/atomfix_controls.py; PRE changes only the five write cuts.
include Makefile
.PHONY: atomfix-controls
atomfix-controls: build/tomokv-atomfix-pre build/atomic-plain-pre-unit
ATOMFIX_PRE := build/atomfix-pre
ATOMFIX_DEPS := $(wildcard $(ATOMFIX_PRE)/src/*/*.inc) $(wildcard $(ATOMFIX_PRE)/src/*/*.h)
$(ATOMFIX_PRE)/xshard.o: $(ATOMFIX_PRE)/src/cmd/xshard.cc $(ATOMFIX_DEPS)
\t$(CXX) $(CXXFLAGS) $(JEFLAGS) -I. -c $< -o $@
$(ATOMFIX_PRE)/xshard-db0.o: $(ATOMFIX_PRE)/src/cmd/xshard.cc $(ATOMFIX_DEPS)
\t$(CXX) $(CXXFLAGS) $(JEFLAGS) -DTOMO_SINGLE_DATABASE=1 -Dtomo=tomo_db0 -I. -c $< -o $@
build/tomokv-atomfix-pre: $(OBJ) $(DB0_OBJ) $(ATOMFIX_PRE)/xshard.o $(ATOMFIX_PRE)/xshard-db0.o
\t$(CXX) $(CXXFLAGS) $(filter-out build/db0/src/cmd/xshard.o,$(DB0_OBJ)) $(ATOMFIX_PRE)/xshard-db0.o $(filter-out build/src/cmd/xshard.o,$(OBJ)) $(ATOMFIX_PRE)/xshard.o -o $@ $(JELIBS) $(LDLIBS) -lm
build/atomic-plain-pre-unit: tests/atomic_survivors_unit.cc tests/atomic_plain_checks.inc tests/atomiccollapse_checks.inc $(ATOMFIX_DEPS) $(filter-out build/src/main.o build/src/cmd/xshard.o,$(OBJ))
\t$(CXX) $(CXXFLAGS) $(JEFLAGS) -I$(ATOMFIX_PRE) -I. tests/atomic_survivors_unit.cc $(filter-out build/src/main.o build/src/cmd/xshard.o,$(OBJ)) -o $@ $(JELIBS) $(LDLIBS) -lm
""")
    print("Prepared build/atomfix-controls.mk and five-cut PRE source twin")


if __name__ == "__main__":
    main()
