#pragma once
// Numeric TEXT: the one place that turns a double into the bytes redis 7.4 puts on the wire, and
// the one place that turns client bytes back into a double the way redis accepts them.
//
// Both directions used to be "whatever the standard library does", and both were observably wrong
// against the reference:
//
//   * FORMAT. std::to_chars gives the shortest round-trip digits. Redis renders every double
//     through fpconv_dtoa, which is Grisu2 (Loitsch, "Printing Floating-Point Numbers Quickly and
//     Accurately with Integers", PLDI 2010). Grisu2 is round-trip correct but NOT always shortest,
//     so its digit string differs from to_chars' in the last place, or in length, for roughly one
//     double in 700: 1e126 is "9.999999999999999e+125" there and "1e+126" with to_chars.
//     grisu2_digits() below is that algorithm, written from the published description and from the
//     7.4 binary's observed output; no reference source was read.
//
//   * PARSE. Redis does not have one float grammar, it has three, and which one applies depends on
//     the argument. parse_double_strict() is the getDoubleFromObject grammar (ZADD score, weights,
//     GEO coordinates); parse_double_lenient() is the bare strtod that zslParseRange uses for score
//     RANGES and that sortCommand uses for numeric SORT. They differ on inputs clients really send:
//     "" is a range error to one and 0.0 to the other. Both accept the hexadecimal spellings strtod
//     accepts, because strtod is what redis calls.
//
// Everything here is header-only and out of the GET/SET path; the hot dispatch never calls it.

#include <cctype>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>

#include "src/base/slice.h"

namespace tomo {
namespace dtoa {

// ------------------------------------------------------------------ Grisu2 digit generation

// A "diy fp": the value f * 2^e, with f carried at full 64-bit width so the multiply below keeps
// the extra guard bits Grisu2 needs.
struct Fp {
    uint64_t f;
    int e;
};

struct CachedPow {
    uint64_t f;
    int16_t e;
    int16_t k;   // decimal exponent: this row is 10^k, rounded to 64 significant bits
};

// 10^-348 .. 10^340 in steps of 8. Generated by exact rational arithmetic, not transcribed:
// f = round(10^k / 2^e) with f in [2^63, 2^64).  87 rows is exactly enough that every binary
// exponent a double can have lands inside the target window below.
inline constexpr CachedPow kPow10[87] = {
    {0xfa8fd5a0081c0288ULL, -1220,  -348},    {0xbaaee17fa23ebf76ULL, -1193,  -340},
    {0x8b16fb203055ac76ULL, -1166,  -332},    {0xcf42894a5dce35eaULL, -1140,  -324},
    {0x9a6bb0aa55653b2dULL, -1113,  -316},    {0xe61acf033d1a45dfULL, -1087,  -308},
    {0xab70fe17c79ac6caULL, -1060,  -300},    {0xff77b1fcbebcdc4fULL, -1034,  -292},
    {0xbe5691ef416bd60cULL, -1007,  -284},    {0x8dd01fad907ffc3cULL,  -980,  -276},
    {0xd3515c2831559a83ULL,  -954,  -268},    {0x9d71ac8fada6c9b5ULL,  -927,  -260},
    {0xea9c227723ee8bcbULL,  -901,  -252},    {0xaecc49914078536dULL,  -874,  -244},
    {0x823c12795db6ce57ULL,  -847,  -236},    {0xc21094364dfb5637ULL,  -821,  -228},
    {0x9096ea6f3848984fULL,  -794,  -220},    {0xd77485cb25823ac7ULL,  -768,  -212},
    {0xa086cfcd97bf97f4ULL,  -741,  -204},    {0xef340a98172aace5ULL,  -715,  -196},
    {0xb23867fb2a35b28eULL,  -688,  -188},    {0x84c8d4dfd2c63f3bULL,  -661,  -180},
    {0xc5dd44271ad3cdbaULL,  -635,  -172},    {0x936b9fcebb25c996ULL,  -608,  -164},
    {0xdbac6c247d62a584ULL,  -582,  -156},    {0xa3ab66580d5fdaf6ULL,  -555,  -148},
    {0xf3e2f893dec3f126ULL,  -529,  -140},    {0xb5b5ada8aaff80b8ULL,  -502,  -132},
    {0x87625f056c7c4a8bULL,  -475,  -124},    {0xc9bcff6034c13053ULL,  -449,  -116},
    {0x964e858c91ba2655ULL,  -422,  -108},    {0xdff9772470297ebdULL,  -396,  -100},
    {0xa6dfbd9fb8e5b88fULL,  -369,   -92},    {0xf8a95fcf88747d94ULL,  -343,   -84},
    {0xb94470938fa89bcfULL,  -316,   -76},    {0x8a08f0f8bf0f156bULL,  -289,   -68},
    {0xcdb02555653131b6ULL,  -263,   -60},    {0x993fe2c6d07b7facULL,  -236,   -52},
    {0xe45c10c42a2b3b06ULL,  -210,   -44},    {0xaa242499697392d3ULL,  -183,   -36},
    {0xfd87b5f28300ca0eULL,  -157,   -28},    {0xbce5086492111aebULL,  -130,   -20},
    {0x8cbccc096f5088ccULL,  -103,   -12},    {0xd1b71758e219652cULL,   -77,    -4},
    {0x9c40000000000000ULL,   -50,     4},    {0xe8d4a51000000000ULL,   -24,    12},
    {0xad78ebc5ac620000ULL,     3,    20},    {0x813f3978f8940984ULL,    30,    28},
    {0xc097ce7bc90715b3ULL,    56,    36},    {0x8f7e32ce7bea5c70ULL,    83,    44},
    {0xd5d238a4abe98068ULL,   109,    52},    {0x9f4f2726179a2245ULL,   136,    60},
    {0xed63a231d4c4fb27ULL,   162,    68},    {0xb0de65388cc8ada8ULL,   189,    76},
    {0x83c7088e1aab65dbULL,   216,    84},    {0xc45d1df942711d9aULL,   242,    92},
    {0x924d692ca61be758ULL,   269,   100},    {0xda01ee641a708deaULL,   295,   108},
    {0xa26da3999aef774aULL,   322,   116},    {0xf209787bb47d6b85ULL,   348,   124},
    {0xb454e4a179dd1877ULL,   375,   132},    {0x865b86925b9bc5c2ULL,   402,   140},
    {0xc83553c5c8965d3dULL,   428,   148},    {0x952ab45cfa97a0b3ULL,   455,   156},
    {0xde469fbd99a05fe3ULL,   481,   164},    {0xa59bc234db398c25ULL,   508,   172},
    {0xf6c69a72a3989f5cULL,   534,   180},    {0xb7dcbf5354e9beceULL,   561,   188},
    {0x88fcf317f22241e2ULL,   588,   196},    {0xcc20ce9bd35c78a5ULL,   614,   204},
    {0x98165af37b2153dfULL,   641,   212},    {0xe2a0b5dc971f303aULL,   667,   220},
    {0xa8d9d1535ce3b396ULL,   694,   228},    {0xfb9b7cd9a4a7443cULL,   720,   236},
    {0xbb764c4ca7a44410ULL,   747,   244},    {0x8bab8eefb6409c1aULL,   774,   252},
    {0xd01fef10a657842cULL,   800,   260},    {0x9b10a4e5e9913129ULL,   827,   268},
    {0xe7109bfba19c0c9dULL,   853,   276},    {0xac2820d9623bf429ULL,   880,   284},
    {0x80444b5e7aa7cf85ULL,   907,   292},    {0xbf21e44003acdd2dULL,   933,   300},
    {0x8e679c2f5e44ff8fULL,   960,   308},    {0xd433179d9c8cb841ULL,   986,   316},
    {0x9e19db92b4e31ba9ULL,  1013,   324},    {0xeb96bf6ebadf77d9ULL,  1039,   332},
    {0xaf87023b9bf0ee6bULL,  1066,   340},
};

inline constexpr uint64_t kTens[20] = {
    10000000000000000000ULL, 1000000000000000000ULL, 100000000000000000ULL,
    10000000000000000ULL,    1000000000000000ULL,    100000000000000ULL,
    10000000000000ULL,       1000000000000ULL,       100000000000ULL,
    10000000000ULL,          1000000000ULL,          100000000ULL,
    10000000ULL,             1000000ULL,             100000ULL,
    10000ULL,                1000ULL,                100ULL,
    10ULL,                   1ULL,
};

// The top 64 bits of a*b, with the discarded half rounded in. Grisu2 depends on this exact
// rounding: it is what makes the boundary arithmetic below conservative rather than merely close.
inline Fp fp_multiply(Fp a, Fp b) {
    const unsigned __int128 product = static_cast<unsigned __int128>(a.f) * b.f;
    const uint64_t high = static_cast<uint64_t>(product >> 64);
    const uint64_t low = static_cast<uint64_t>(product);
    return Fp{high + (low >> 63), a.e + b.e + 64};
}

// The cached power whose product with a value of this binary exponent lands the result in
// [2^-60, 2^-32) of the "one" unit -- the window Grisu2's two digit loops are written for.
inline int cached_pow_index(int exponent) {
    // 1/log2(10): converts a binary exponent into the decimal exponent that lands nearby, so the
    // scan below starts on or next to the answer instead of walking 87 rows.
    // The truncation happens BEFORE the offset is added, and the scan below is not free to land
    // wherever it likes: the 8-decimal row spacing is ~26.6 binary and the window is 29 wide, so
    // for some exponents two adjacent rows both qualify and the starting point decides which one
    // is used -- and which one is used decides the last digit.
    constexpr double kInvLog2Of10 = 0.30102999566398114;
    int index = (static_cast<int>(-(exponent + 87) * kInvLog2Of10) + 348) / 8;
    if (index < 0) index = 0;
    if (index > 86) index = 86;
    for (;;) {
        const int scaled = exponent + kPow10[index].e + 64;
        if (scaled < -60) { index++; continue; }
        if (scaled > -32) { index--; continue; }
        return index;
    }
}

// Trim the last digit down while every candidate still round-trips and the shorter one is closer
// to w. This is Grisu2's "weeding" step; without it the last digit is merely inside the boundary
// interval rather than the one redis prints.
inline void weed_last_digit(char* digits, int count, uint64_t delta, uint64_t remainder,
                            uint64_t unit, uint64_t distance) {
    while (remainder < distance && delta - remainder >= unit &&
           (remainder + unit < distance || distance - remainder > remainder + unit - distance)) {
        digits[count - 1]--;
        remainder += unit;
    }
}

// Writes the decimal digits of `value` (finite, non-zero) into `digits` and sets `k` so that
// value == digits * 10^k. Returns the digit count (at most 18). Sign is the caller's business.
inline int grisu2_digits(double value, char* digits, int& k) {
    uint64_t bits;
    std::memcpy(&bits, &value, sizeof(bits));
    const int biased = static_cast<int>((bits >> 52) & 0x7FF);
    const uint64_t mantissa = bits & ((uint64_t{1} << 52) - 1);

    Fp w = biased ? Fp{mantissa + (uint64_t{1} << 52), biased - 1075} : Fp{mantissa, -1074};

    // The normalized boundaries: the halfway points to the neighbouring doubles, both carried at
    // the same exponent so their difference is the interval any correct digit string may land in.
    Fp upper{(w.f << 1) + 1, w.e - 1};
    while ((upper.f & (uint64_t{1} << 53)) == 0) { upper.f <<= 1; upper.e--; }
    upper.f <<= 10;
    upper.e -= 10;

    const int lower_shift = (w.f == (uint64_t{1} << 52)) ? 2 : 1;
    Fp lower{(w.f << lower_shift) - 1, w.e - lower_shift};
    lower.f <<= lower.e - upper.e;
    lower.e = upper.e;

    while ((w.f & (uint64_t{1} << 63)) == 0) { w.f <<= 1; w.e--; }

    const CachedPow& power = kPow10[cached_pow_index(upper.e)];
    const Fp scale{power.f, power.e};
    w = fp_multiply(w, scale);
    upper = fp_multiply(upper, scale);
    lower = fp_multiply(lower, scale);
    // One unit in from each side: the multiply rounded, so the interval is only trustworthy when
    // it is narrowed by the rounding error it may have gained.
    lower.f++;
    upper.f--;
    k = -power.k;

    const uint64_t distance = upper.f - w.f;
    uint64_t delta = upper.f - lower.f;
    const int shift = -upper.e;
    const uint64_t one = uint64_t{1} << shift;

    uint64_t integral = upper.f >> shift;
    uint64_t fractional = upper.f & (one - 1);
    int count = 0;

    // Digits above the decimal point of the scaled value: kappa counts down from 10 because the
    // window above guarantees the integral part is under 10^10.
    int kappa = 10;
    for (const uint64_t* divisor = kTens + 10; kappa > 0; divisor++) {
        const uint64_t div = *divisor;
        const unsigned digit = static_cast<unsigned>(integral / div);
        if (digit || count) digits[count++] = static_cast<char>('0' + digit);
        integral -= digit * div;
        kappa--;
        const uint64_t remainder = (integral << shift) + fractional;
        if (remainder <= delta) {
            k += kappa;
            weed_last_digit(digits, count, delta, remainder, div << shift, distance);
            return count;
        }
    }

    // Digits below it.
    const uint64_t* unit = kTens + 18;
    for (;;) {
        fractional *= 10;
        delta *= 10;
        kappa--;
        const unsigned digit = static_cast<unsigned>(fractional >> shift);
        if (digit || count) digits[count++] = static_cast<char>('0' + digit);
        fractional &= one - 1;
        if (fractional < delta) {
            k += kappa;
            weed_last_digit(digits, count, delta, fractional, one, distance * *unit);
            return count;
        }
        unit--;
    }
}

}  // namespace dtoa

// ------------------------------------------------------------------ the wire text

// Decimal digits, then redis's own fixed/scientific rule. u64_to_dec lives in the RESP header, so
// the plain-integer paths are spelled out here to keep this unit free of protocol includes.
inline uint32_t u64_digits(char* out, uint64_t value) {
    char scratch[20];
    int n = 0;
    do { scratch[n++] = static_cast<char>('0' + value % 10); value /= 10; } while (value);
    for (int i = 0; i < n; i++) out[i] = scratch[n - 1 - i];
    return static_cast<uint32_t>(n);
}

// THE canonical double text, for RESP2 bulk scores and the RESP3 "," form alike (redis renders
// both from one d2string). Derived from the 7.4 binary's OBSERVED output, not from its source:
//
//   * nan / inf / -inf and a signed zero are spelled out;
//   * an INTEGRAL value with |v| <= 4611686018427387904 (redis's (double)(LLONG_MAX/2) bound,
//     probed inclusive at both ends) prints as a plain integer -- so 1e18 is "1000000000000000000",
//     not "1e+18", and 2^62 prints its exact 19 digits while 2^63 does not;
//   * everything else is the Grisu2 digit string D with v = D x 10^K, rendered fixed when K is
//     small and scientific otherwise, with an unpadded signed exponent.
//
// Callers must give at least kDoubleTextMax bytes; the `cap` argument is kept so a call site
// reads as a bounded write, and the sizes are static_asserted where reply buffers are declared.
inline constexpr size_t kDoubleTextMax = 40;

inline uint32_t redis_double_text(char* out, size_t cap, double value) {
    if (std::isnan(value)) { std::memcpy(out, "nan", 3); return 3; }
    if (std::isinf(value)) {
        if (value < 0) { std::memcpy(out, "-inf", 4); return 4; }
        std::memcpy(out, "inf", 3); return 3;
    }
    if (value == 0) {
        if (std::signbit(value)) { std::memcpy(out, "-0", 2); return 2; }
        out[0] = '0';
        return 1;
    }
    // The integral fast path. The bound is redis's (double)(LLONG_MAX/2), which rounds to 2^62.
    constexpr double kIntegralBound = 4611686018427387904.0;
    if (value >= -kIntegralBound && value <= kIntegralBound) {
        const long long integral = static_cast<long long>(value);
        if (static_cast<double>(integral) == value) {
            char* q = out;
            unsigned long long magnitude;
            if (integral < 0) {
                *q++ = '-';
                magnitude = 0ULL - static_cast<unsigned long long>(integral);
            } else {
                magnitude = static_cast<unsigned long long>(integral);
            }
            q += u64_digits(q, magnitude);
            return static_cast<uint32_t>(q - out);
        }
    }

    const bool negative = value < 0;
    char digits[24];
    int k = 0;
    const int ndigits = dtoa::grisu2_digits(negative ? -value : value, digits, k);

    const int decimal_exponent = k + ndigits - 1;   // value == 0.d... x 10^(decimal_exponent+1)
    const int magnitude = decimal_exponent < 0 ? -decimal_exponent : decimal_exponent;
    // Neither branch below can be long. The plain-integer arm pads at most 7 zeroes (that is its
    // own entry condition), the fixed arm at most 3 leading zeroes (a magnitude under 4 is what
    // lets it run at all), and the scientific arm writes a 3-digit exponent. Worst case is
    // sign + 18 digits + 7 padding zeroes = 26 bytes, so kDoubleTextMax covers every value and no
    // length check is needed on the hot path.
    (void)cap;
    char* q = out;
    if (negative) *q++ = '-';
    if (k >= 0 && magnitude < ndigits + 7) {          // plain integer, zero padded
        std::memcpy(q, digits, static_cast<size_t>(ndigits));
        q += ndigits;
        std::memset(q, '0', static_cast<size_t>(k));
        q += k;
    } else if (k < 0 && (k > -7 || magnitude < 4)) {  // fixed point
        const int offset = ndigits + k;
        if (offset <= 0) {
            *q++ = '0';
            *q++ = '.';
            std::memset(q, '0', static_cast<size_t>(-offset));
            q += -offset;
            std::memcpy(q, digits, static_cast<size_t>(ndigits));
            q += ndigits;
        } else {
            std::memcpy(q, digits, static_cast<size_t>(offset));
            q += offset;
            *q++ = '.';
            std::memcpy(q, digits + offset, static_cast<size_t>(ndigits - offset));
            q += ndigits - offset;
        }
    } else {                                          // scientific, exponent not zero padded
        *q++ = digits[0];
        if (ndigits > 1) {
            *q++ = '.';
            std::memcpy(q, digits + 1, static_cast<size_t>(ndigits - 1));
            q += ndigits - 1;
        }
        *q++ = 'e';
        *q++ = decimal_exponent < 0 ? '-' : '+';
        q += u64_digits(q, static_cast<uint64_t>(magnitude));
    }
    return static_cast<uint32_t>(q - out);
}

// ------------------------------------------------------------------ parsing

// The redis getDoubleFromObject grammar, used wherever a double is a VALUE: ZADD/ZINCRBY scores,
// ZUNIONSTORE weights, GEO coordinates and distances. Redis calls strtod and then refuses the
// empty string, a leading space, trailing text, a magnitude strtod flagged as out of range, and
// NaN. It does NOT refuse what strtod itself accepts, so "0x10" is 16 and "+5" is 5.
//
// The slice is copied because strtod needs a terminator; an embedded NUL therefore leaves trailing
// text behind and is refused, which is the same answer redis gives (it compares the consumed
// length against the whole argument length).
inline bool parse_double_strict(Slice s, double& out) {
    char text[512];
    if (s.n == 0 || s.n >= sizeof(text)) return false;
    std::memcpy(text, s.p, s.n);
    text[s.n] = '\0';
    if (std::isspace(static_cast<unsigned char>(text[0]))) return false;

    errno = 0;
    char* end = nullptr;
    const double value = std::strtod(text, &end);
    if (end != text + s.n) return false;
    if (errno == ERANGE && (std::isinf(value) || std::fpclassify(value) == FP_ZERO)) return false;
    if (std::isnan(value)) return false;
    out = value;
    return true;
}

// The bare strtod redis uses for score RANGES (zslParseRange) and for numeric SORT. Everything the
// strict grammar refuses is accepted here except NaN and trailing text:
//
//   ""       -> 0      (strtod consumed nothing, and the terminator is where it stopped)
//   " 5"     -> 5      (strtod skips leading whitespace)
//   "0x10"   -> 16
//   "1e309"  -> +inf   (ERANGE is not consulted)
//   "5\0 5"  -> 5      (the C string ends at the NUL, so nothing trails it)
//
// The NUL case is not an oversight to be corrected: redis stops at the same byte and answers 5,
// and a range that answered an error where the reference answers a result would silently change
// which members a client sees.
inline bool parse_double_lenient(Slice s, double& out) {
    char text[512];
    if (s.n >= sizeof(text)) return false;
    std::memcpy(text, s.p, s.n);
    text[s.n] = '\0';

    char* end = nullptr;
    const double value = std::strtod(text, &end);
    if (*end != '\0' || std::isnan(value)) return false;
    out = value;
    return true;
}

}  // namespace tomo
