"""Source-only expansion of the two folded differential gate rows."""
import ast
from pathlib import Path


def reviews(root):
    source = (root / "tests/differ.py").read_text()
    tree = ast.parse(source)
    functions = {node.name: node.lineno for node in tree.body
                 if isinstance(node, ast.FunctionDef)}
    generators = next(node.value for node in tree.body if isinstance(node, ast.Assign)
                      and any(isinstance(t, ast.Name) and t.id == "gens" for t in node.targets))
    suites = {key.value: value.id for key, value in zip(generators.keys, generators.values)}
    property_functions = {
        "blocking": "run_blocking_differ", "pubsub": "run_pubsub_differ",
        "fanout": "run_fanout_differ", "spubsub": "run_spubsub_differ",
        "notify": "run_notify_suite", "wiredump": "run_wiredump_suite",
        "climon": "run_climon_suite", "compatintro": "run_compatintro_suite",
        "aclsel": "run_aclsel_suite", "cmdmeta": "run_cmdmeta_suite",
        "s6fix": "run_s6fix_suite", "ccfix": None, "psfix": "run_psfix_suite",
    }
    suites.update(property_functions)
    # Validate against the declared --list-generators branch without running differ.py.
    list_branch = next(node for node in tree.body if isinstance(node, ast.If)
                       and isinstance(node.test, ast.Name) and node.test.id == "LIST_GENERATORS"
                       and node.lineno > functions["run_psfix_suite"])
    declared = next(node for node in ast.walk(list_branch) if isinstance(node, ast.List))
    assert [node.value for node in declared.elts] == list(property_functions)
    assert len(suites) == 44
    D, B, L = "DETERMINISTIC", "BOUNDED-WITNESSED", "LOTTERY"
    ordinary = "Ordered exact replies on clean namespaces; seeded command diversity is not a required race witness."
    special = {
        "hexpire": (D, "Absolute deadlines are far future or already past; TTL replies are checked against each peer's measured request interval."),
        "edgetime": (D, "Past/far-future deadlines and independent request/reply clock brackets; no cross-peer fixed TTL tolerance."),
        "stream": (L, "Auto-ID property at differ.py:6664 samples wall time once, then requires every ID within 10 seconds; needs per-request server-clock bracketing."),
        "geo": (B, "Fresh-key bounded LFU arming, required metadata deltas, and observed cross-owner placement; policy and budget are restored."),
        "sort": (D, "Actual generated BY/GET keys must cross known owners before the exact reply stream is run; fused geometry explicitly excludes this suite."),
        "infofix": (B, "Every RESETSTAT establishes a new baseline; positive/idle published rates and final reset are bounded required observations."),
        "multidb": (B, "SWAPDB and SELECT are ordered; final SELECT 0/FLUSHALL creates an exact nonzero population, followed by required published-DBSIZE convergence."),
        "blocking": (L, "Collection blockers use required parked/drained gauges, but WAIT 200 sleeps 50 ms and then requires wire silence. Descheduling across the deadline fails; needs fresh deadline arming."),
        "pubsub": (B, "Subscription acknowledgements precede exact delivery/count assertions and bounded receipt; absent delivery fails."),
        "spubsub": (B, "Shard subscription acknowledgements precede the exact publish and delivery oracle; missing messages fail."),
        "fanout": (B, "Acknowledged subscriber topology precedes required per-peer delivery; socket bounds are liveness bounds."),
        "notify": (B, "Acknowledged subscription and config precede the exact expected event count; no live expiry-window lottery in this selection."),
        "climon": (L, "Tracking pushes at differ.py:5076 are delimited by 1.2-second/200-ms idle reads, not an ordered fence; late pushes can move between legs. Needs a delivery fence."),
        "compatintro": (B, "Directed introspection/config/ACL cases and exact notification counts; expiry sleep follows an armed 1-ms deadline and has no upper live-window condition."),
        "s6fix": (L, "Each peer must cover all 200 keys in 20,000 RANDOMKEY draws; finite sampling cannot guarantee coverage. Needs a controllable sampler witness."),
        "ccfix": (B, "Source/predecessor overlap is held by existing DEBUG controls and requires pending/read counters; notification batches are fenced; RESETSTAT baselines are refreshed."),
        "psfix": (B, "Both peers must report save idle in the same bounded polling round before each SAVE/BGSAVE and counter baseline; exact +1 counters retained."),
    }
    result = []
    for name, function in suites.items():
        kind, mechanism = special.get(name, (D, ordinary))
        path = "tests/differ.py" if function else "tests/_differ_ccfix.py"
        line = functions[function] if function else 1
        result.append(dict(name=name, site=f"{path}:{line}", kind=kind, mechanism=mechanism))
    return result
